apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.k8s.name }}
  namespace: {{ .Values.k8s.namespace }}
  labels:
      app.kubernetes.io/managed-by: Helm
  annotations:
      meta.helm.sh/release-name: {{ .Values.k8s.name }}
      meta.helm.sh/release-namespace: {{ .Values.k8s.namespace }}
spec:
  selector:
    fanbook.com/wenjuan: "server"
  ports:
    - name: api
      port: {{ .Values.server.port }}
      protocol: TCP
      targetPort: {{ .Values.server.port }}
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.k8s.name }}
  namespace: {{ .Values.k8s.namespace }}
  labels:
      app.kubernetes.io/managed-by: Helm
  annotations:
      meta.helm.sh/release-name: {{ .Values.k8s.name }}
      meta.helm.sh/release-namespace: {{ .Values.k8s.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fanbook.com/wenjuan: "server"
  template:
    metadata:
      name: {{ .Values.k8s.name }}
      labels:
        fanbook.com/wenjuan: "server"
    spec:
      containers:
        - image: {{ .Values.k8s.image }}
          imagePullPolicy: Always
          name: {{ .Values.k8s.name }}
          #command: ["/bin/bash"]
          #args: ["-c", "while true; do sleep 10;done"]
          #securityContext:
          #  privileged: true
          volumeMounts:
          - name: timezone
            mountPath: /etc/localtime                           # 挂载到容器的目录
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai               # 宿主机的目录
      enableServiceLinks: false
      restartPolicy: Always
