name: build-compiler-main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    container: tarscloud/base-compiler
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.name }}
          password: ${{ secrets.pass }}
      -  name: Install SSH Key
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.ACTION_DEPLOY_KEY }}
           name: ssh_tarstime_key
           known_hosts: ${{ secrets.ACTION_KNOWN_HOSTS }}
           config: ${{ secrets.ACTION_DEPLOY_CONFIG }}
           if_key_exists: replace
      -   name: Set Outputs
          id: vars
          run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: compile server
        run: |
          mvn clean install -DskipTests
          cd tduck-api
          mvn clean package -DskipTests
      - name: build docker
        run: |
          cd tduck-api
          docker build -t jaminzou/fanbook-wenjuan-server:${{ steps.vars.outputs.sha_short }} .
          docker push jaminzou/fanbook-wenjuan-server:${{ steps.vars.outputs.sha_short }}
      - name: build helm
        run: |
          export RemoteImagesTag=${{ steps.vars.outputs.sha_short }}
          sed -i 's#${image-tag}#'${RemoteImagesTag}'#g' helm/values.yaml
          helm package helm -d .
      - name: scp helm
        run: |
          ssh -p 22000 tarstime "rm -f /home/ubuntu/fanbook/fanbook-wenjuan-server-*.tgz"
          scp -P 22000 fanbook-wenjuan-server-${{ steps.vars.outputs.sha_short }}.tgz tarstime:/home/ubuntu/fanbook/
      - name: deploy
        run: ssh -p 22000 tarstime "helm upgrade --install fanbook-wenjuan-server /home/ubuntu/fanbook/fanbook-wenjuan-server-${{ steps.vars.outputs.sha_short }}.tgz"
